apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-deploy
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-deploy
    spec:
      containers:
      - name: auth-deploy
        image: taharamakda/auth:v3
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_AUTH_URI
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: MONGODB_AUTH_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-credentials
              key: JWT_SECRET
        resources:
          limits:
            memory: 256Mi
            cpu: 0.4
