apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.44.0
        args:
        - "--mongodb.uri=mongodb://localhost:27017"
        ports:
        - containerPort: 9216
      volumes:
      - name: mongo-data
        hostPath:
          path: /tmp/mongo-data
          type: Directory
