apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus-scrape: auth
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus-scrape: order
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus-scrape: product
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus-scrape: rabbitmq
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
