apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    prometheus-scrape: auth
spec:
  selector:
    app: auth-deploy
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    prometheus-scrape: product
spec:
  selector:
    app: product-deploy
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: order-svc
  labels:
    prometheus-scrape: order
spec:
  selector:
    app: order-deploy
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-service
  ports:
  - name: app
    port: 27017
    targetPort: 27017
  - name: http
    port: 9216
    targetPort: 9216
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    prometheus-scrape: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  - name: http
    port: 9419
    targetPort: 9419
  type: NodePort
