apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth-deploy
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-deploy
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product-deploy
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-service
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  type: NodePort
