apiVersion: v1
kind: Pod
metadata:
  name: init-hostpath
spec:
  containers:
  - name: setup
    image: busybox
    command: [ "sh", "-c", "mkdir -p /tmp/mongo-data /tmp/rabbitmq-data && sleep 300" ]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp
      name: host-tmp
  volumes:
  - name: host-tmp
    hostPath:
      path: /tmp
      type: Directory
  restartPolicy: Never
